### ISSUE TITLE
!so command

### ISSUE THREAD

**Issue by totti240282** [albx/KITT#11]
comando per seguire un canale twitch che ti ha fatto il raid o hosting

Esempio:

!so totti
=> Andate a seguire totti sul suo canale www.twitch.tv/totti

**Comment by albx** [comment]
@totti240282 Ho creato la PR #14 per questo refactor, se ti va di dare un'occhiata e fare una review veloce mi farebbe davvero piacere :)

**Comment by totti240282** [comment]
Perfetto!
